# Generated by Django 5.0.6 on 2024-05-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_sold', models.IntegerField()),
                ('product_sales', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('total_quantity', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('sales_percentage', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('monthly_sales', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
