# Generated by Django 5.0.6 on 2024-05-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='product_id',
        ),
    ]
