# Generated by Django 5.0.6 on 2024-05-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportlist', '0002_remove_salesreport_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='product_name',
        ),
    ]
