# Generated by Django 5.0.6 on 2024-05-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportlist', '0003_remove_salesreport_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
